using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KRtDL_Level_Randomizer.ext
{
    public static class Objects
    {
        public static readonly Dictionary<uint, string> GimmickList = new Dictionary<uint, string>()
        {
            {0, "Door" },
            {1, "Falling Background Object" },
            {2, "Guide Sign" },
            {3, "Locked Shutter Door" },
            {4, "Pop Flower" },
            {5, "Start Point" },
            {6, "Dimension Hole" },
            {7, "Warp Star" },
            {8, "Arrow Sign" },
            {9, "Stage Select Door" },
            {10, "Rope Platform" },
            {11, "Camera" },
            {12, "Another Dimension Wall" },
            {14, "Wooden Stake" },
            {15, "One-Time Switch" },
            {16, "Toggle Switch" },
            {17, "Timer Switch" },
            {18, "Bomb Block Chain Starter" },
            {19, "Blast Cannon" },
            {20, "Invisibility Stone Gate" },
            {26, "Fuse" },
            {27, "Fuse Cannon" },
            {28, "Statue Block" },
            {29, "Giant Rope" },
            {30, "Shutter Door" },
            {31, "Light Block" },
            {32, "Hang Switch" },
            {34, "Hang Rope" },
            {35, "Flare Beam Switch" },
            {36, "Lor Starcutter" },
            {37, "Magolor" },
            {38, "Lor Starcutter Arrow Sign" },
            {39, "Large Wooden Stake" },
            {40, "Grand Hammer Spring" },
            {41, "Lor Starcutter Monitor" },
            {42, "Pushing Wind" },
            {43, "Challenge Stage Door" },
            {44, "Trigger Area"},
            {45, "Pushing Bubbles" },
            {46, "Dropping Hazard" },
            {47, "Spinning Bar Hazard" },
            {48, "Breakable Roof" },
            {49, "Giant Bomb Machine" },
            {51, "Giant Bell" },
            {52, "Flare Beam Focus" },
            {53, "Rolling Rock Obstacle" },
            {54, "Rolling Spike Ball Obstacle" },
            {55, "Totem Pole Block" },
            {56, "Rolling Spike Wheel Obstacle" },
            {57, "Sandcastle Block" },
            {58, "Lor Starcutter Door" },
            {59, "Moving Tile Support" },
            {60, "Bite Statue" },
            {61, "Pirate Ship Octopus" },
            {62, "Rolling Shell Obstacle" },
            {63, "Press Machine" },
            {64, "BG Popstar Portal" },
            {66, "Strike Box" },
            {68, "Lava Geyser" },
            {69, "Rolling Ice Ball Obstacle" },
            {70, "Giant Bowling Pin" },
            {71, "Confetti Ball" },
            {72, "Medium Wooden Stake" },
            {73, "Midboss Team Controller" },
            {74, "Snowman Body" },
            {75, "Multiplayer Start Point" },
            {76, "Warpstar Starting Point" },
            {77, "Circuit End" },
            {78, "Circuit Block" },
            {79, "Dangerous Dinner Sun/AD Meteo" },
            {80, "Injection Box" },
            {82, "Salamander Head" },
            {83, "Salamander Part" },
            {84, "Key Dee" },
            {85, "Sliceable Volcano" },
            {86, "Landia Room Transition Marker" },
            {87, "Sliceable Magma Pillar" },
            {88, "Freezable Volcano" },
            {90, "Super Enemy Spawner" }
        };
        public static readonly Dictionary<uint, string> CarriablesList = new Dictionary<uint, string>()
        {
            {0, "Bouncing Ability Star" },
            {1, "Key" },
            {2, "Maxim Tomato Box" },
            {3, "Candle" },
            {4, "Cracker" },
            {5, "Invisibility Stone" },
            {6, "Balloon Bomb" },
            {7, "Stomper Boot" },
            {8, "Prism Shield" },
            {9, "Maxim Tomato Box (Alt)" },
        };
        public static readonly Dictionary<uint, string> ItemList = new Dictionary<uint, string>()
        {
            {0, "Point Star" },
            {1, "Extra Life" },
            {2, "Maxim Tomato" },
            {3, "Food" },
            {4, "Energy Sphere" },
            {5, "Invincible Candy" },
            {6, "Red Point Star" },
            {7, "Blue Point Star" },
            {8, "Copy Essence" },
            {9, "Challenge Coin" },
            {10, "Maxim Tomato (Alt)" },
            {11, "Lor Part" },
            {12, "Super Ability Star" },
            {13, "Energy Sphere (Red Point Star)" },
            {14, "Energy Sphere (Empty)" },
        };
        public static readonly Dictionary<uint, string> BossList = new Dictionary<uint, string>()
        {
            {0, "Sphere Doomer" },
            {1, "Whispy Woods" },
            {2, "Gigant Edge" },
            {3, "Mr. Dooter" },
            {4, "Water Galboros" },
            {5, "King Doo" },
            {6, "Kibble Blade" },
            {7, "Bonkers" },
            {8, "Dubior" },
            {9, "Grand Doomer" },
            {10, "Moundo" },
            {11, "Metal General" },
            {12, "Fatty Puffer" },
            {13, "Goriath" },
            {14, "Lor Starcutter" },
            {15, "Magolor" },
            {16, "Landia" },
            {17, "Unknown" },
            {18, "Magolor Soul" },
            {19, "HR-D3/Metal General (Story)" },
            {20, "Galacta Knight" },
        };
        public static readonly Dictionary<uint, string> EnemyList = new Dictionary<uint, string>()
        {
            {0, "Sir Kibble" },
            {1, "Bronto Burt" },
            {2, "Waddle Dee" },
            {3, "Blade Knight" },
            {4, "Cappy" },
            {5, "Hothead" },
            {6, "Knuckle Joe" },
            {7, "Puppet Dee" },
            {8, "Armor Dee" },
            {9, "Como" },
            {10, "Gordo" },
            {11, "Togekuki" },
            {12, "Whippy" },
            {13, "Pacto" },
            {14, "Shotzo" },
            {15, "Leafan" },
            {16, "Waddle Doo" },
            {17, "Bouncy" },
            {18, "Sparky" },
            {19, "Needlous" },
            {20, "Broom Hatter" },
            {21, "Scarfy" },
            {22, "Nruff" },
            {23, "Flamer" },
            {24, "Tick" },
            {25, "Water Galbo" },
            {26, "Rocky" },
            {27, "Bulby" },
            {28, "Starman" },
            {29, "Twister" },
            {30, "Poppy Bros Jr" },
            {31, "Noddy" },
            {32, "Cerulean" },
            {33, "Blipper" },
            {34, "Gigatzo" },
            {35, "Babut" },
            {36, "Glunk" },
            {37, "Bouncy Sis" },
            {39, "Mumbies" },
            {40, "Parasol Waddle Dee" },
            {41, "Kabu" },
            {42, "Parasol Waddle Doo" },
            {43, "Mopoo" },
            {44, "Foley" },
            {45, "Juckle" },
            {46, "Bowby" },
            {47, "Owgulf" },
            {48, "Degout" },
            {49, "Sheld" },
            {50, "Lanzer" },
            {51, "Chilly" },
            {52, "Moonja" },
            {53, "Pluid" },
            {54, "Gemra" },
            {55, "Wapod Pot" },
            {57, "Volttzo" },
            {58, "Barbar" },
            {59, "Barracu" },
            {60, "Squishy" },
            {61, "Clayn" },
            {62, "Pierce" },
            {63, "Searches" },
            {64, "Walky" },
            {65, "Elec" },
            {66, "Rope Waddle Dee" },
            {67, "Rope Waddle Doo" },
            {68, "Sodory" },
            {69, "Galbo" },
            {70, "Snowl" },
            {72, "Halcandle Dee" },
            {73, "Coldtzo" },
            {74, "Coconut Bomb" },
            {75, "Craby" },
            {76, "Pacloud" },
            {77, "Iron Barbar" },
            {78, "Walf" },
            {81, "Larpa" },
            {82, "Liepa" },
            {83, "Lupa" },
            {84, "Leaper" },
            {85, "Halcandran Bronto Burt" },
            {86, "Halcandran Armor Dee" },
            {87, "Waddle Dee on Nruff" },
            {88, "Hunter Degout" },
            {89, "Hunter Scarfy" },
            {90, "Key Dee (Without Key)" },
            {92, "Sandbag" },
            {93, "Parasol Halcandle Dee" },
            {94, "Halcandran Bouncy" },
            {95, "Halcandran Bowby" },
            {101, "Cappy Cap" },
            {102, "Doomer Shot" },
            {103, "Fire Doomer Shot" },
            {104, "Spark Doomer Shot" },
            {105, "Ice Doomer Shot" },
            {106, "Whispy Apple" },
            {107, "Poison Whispy Apple" },
            {108, "Mr. Dooter Skull" },
            {109, "Mr. Dooter Flaming Skull" },
            {110, "Mr. Dooter Snake" },
            {112, "Mr. Dooter Bomb" },
            {113, "Enemy Parasol" },
            {114, "Dubior Jr." },
            {115, "Poppy Jr. Bomb" },
            {116, "Grand Doomer Shot" },
            {117, "Kibble Blade Cutter" },
            {118, "Bonkers Coconut Bomb" },
            {119, "Dubior Spark" },
            {120, "Metal General Drone" },
            {121, "Metal General Drone (Alt)" },
            {122, "Metal General Bomb" },
            {123, "Metal General Missile" },
            {124, "Metal General Patriot Missile" },
            {125, "Metal General Spark Bomb" },
            {126, "Fatty Puffer Jr" },
            {128, "Fatty Puffer Stalactite" },
            {129, "Wapod" },
            {130, "Goriath Snowball" },
            {131, "Goriath Ice Ball" },
            {132, "Goriath Icicle" },
            {133, "Missile" },
            {134, "Magolor Phase 1 Revolution Sphere" },
            {135, "Magolor Phase 1 Projectile Doomer" },
            {145, "Magolor" },
        };

        public static readonly Dictionary<uint, string> DecorationList = new Dictionary<uint, string>()
        {
            {1, "Kamitake" },
            {2, "Hasikura" },
            {3, "Morisita" },
            {4, "Noriko" },
            {5, "Cave" },
            {6, "Grass" },
            {7, "Fujiura" },
            {8, "Log" },
            {9, "GCK Beach" },
            {10, "GCK Canyon" },
            {11, "GCK Snow MT" },
            {12, "Lowper" },
            {13, "Desert" },
            {14, "Cave Normal" },
            {15, "Oasis" },
            {16, "Level Map 1" },
            {17, "Air Fort" },
            {18, "Air Island" },
            {19, "Air Temple" },
            {20, "Beach" },
            {21, "Bridge" },
            {22, "Factory" },
            {23, "GCK Cloud" },
            {24, "Hasiguti" },
            {25, "Hondayu" },
            {26, "Ice Building" },
            {27, "Ice Cave" },
            {28, "Lava" },
            {29, "Minami" },
            {30, "Pyramid" },
            {31, "Sea" },
            {32, "Sea Temple" },
            {33, "Snow" },
            {34, "Subway" },
            {35, "Sun" },
            {36, "Volcano" },
            {37, "H_Itoh" },
            {39, "Lowper2" },
            {40, "Level Map 2" },
            {41, "Level Map 3" },
            {42, "Level Map 4" },
            {43, "Level Map 5" },
            {44, "Level Map 6" },
            {45, "Level Map 7" },
            {46, "Challenge" },
            {47, "Ship" },
            {48, "Shooting" },
            {49, "Final" },
            {50, "Challenge 01" },
            {51, "Challenge 02" },
            {52, "Challenge 03" },
            {53, "Challenge 04" },
            {54, "Challenge 05" },
            {55, "Challenge 06" },
            {56, "Challenge 07" },
            {57, "Landia" },
            {58, "GCK Cloud 2" },
            {59, "Desert 2" },
            {60, "Landia 2" },
            {61, "Room" },
            {62, "Room 2" },
            {63, "GCK Canyon 2" },
            {64, "Halcandra" },
            {65, "Air Temple 2" },
            {66, "Empty" },
            {67, "Hex" },
            {68, "Pop Star" },
            {69, "Sea Temple 2" },
            {70, "Blank" }
        };

        public static readonly Dictionary<string, string> levelFDGs = new Dictionary<string, string>()
        {
            {"StepMapDataLevel1Stage1Step01.dn", "map/step/level1/stage1/Step01.dat"},
            {"StepMapDataLevel1Stage1Step02.dn", "map/step/level1/stage1/Step02.dat"},
            {"StepMapDataLevel1Stage1Step03.dn", "map/step/level1/stage1/Step03.dat"},
            {"StepMapDataLevel1Stage1Step04.dn", "map/step/level1/stage1/Step04.dat"},
            {"StepMapDataLevel1Stage1Step05.dn", "map/step/level1/stage1/Step05.dat"},
            {"StepMapDataLevel1Stage2Step01.dn", "map/step/level1/stage2/Step01.dat"},
            {"StepMapDataLevel1Stage2Step02.dn", "map/step/level1/stage2/Step02.dat"},
            {"StepMapDataLevel1Stage2Step03.dn", "map/step/level1/stage2/Step03.dat"},
            {"StepMapDataLevel1Stage2Step04.dn", "map/step/level1/stage2/Step04.dat"},
            {"StepMapDataLevel1Stage2Step05.dn", "map/step/level1/stage2/Step05.dat"},
            {"StepMapDataLevel1Stage2Step06.dn", "map/step/level1/stage2/Step06.dat"},
            {"StepMapDataLevel1Stage2Step07.dn", "map/step/level1/stage2/Step07.dat"},
            {"StepMapDataLevel1Stage3Step01.dn", "map/step/level1/stage3/Step01.dat"},
            {"StepMapDataLevel1Stage3Step02.dn", "map/step/level1/stage3/Step02.dat"},
            {"StepMapDataLevel1Stage3Step03.dn", "map/step/level1/stage3/Step03.dat"},
            {"StepMapDataLevel1Stage3Step04.dn", "map/step/level1/stage3/Step04.dat"},
            {"StepMapDataLevel1Stage3Step05.dn", "map/step/level1/stage3/Step05.dat"},
            {"StepMapDataLevel1Stage4Step01.dn", "map/step/level1/stage4/Step01.dat"},
            {"StepMapDataLevel1Stage4Step02.dn", "map/step/level1/stage4/Step02.dat"},
            {"StepMapDataLevel1Stage4Step03.dn", "map/step/level1/stage4/Step03.dat"},
            {"StepMapDataLevel1Stage4Step04.dn", "map/step/level1/stage4/Step04.dat"},
            {"StepMapDataLevel1Stage4Step05.dn", "map/step/level1/stage4/Step05.dat"},
            {"StepMapDataLevel1Stage4Step06.dn", "map/step/level1/stage4/Step06.dat"},
            {"StepMapDataLevel1Stage4Step07.dn", "map/step/level1/stage4/Step07.dat"},
            {"StepMapDataLevel1Stage5Step01.dn", "map/step/level1/stage5/Step01.dat"},
            {"StepMapDataLevel2Stage1Step01.dn", "map/step/level2/stage1/Step01.dat"},
            {"StepMapDataLevel2Stage1Step02.dn", "map/step/level2/stage1/Step02.dat"},
            {"StepMapDataLevel2Stage1Step03.dn", "map/step/level2/stage1/Step03.dat"},
            {"StepMapDataLevel2Stage1Step04.dn", "map/step/level2/stage1/Step04.dat"},
            {"StepMapDataLevel2Stage1Step05.dn", "map/step/level2/stage1/Step05.dat"},
            {"StepMapDataLevel2Stage1Step06.dn", "map/step/level2/stage1/Step06.dat"},
            {"StepMapDataLevel2Stage1Step07.dn", "map/step/level2/stage1/Step07.dat"},
            {"StepMapDataLevel2Stage1Step08.dn", "map/step/level2/stage1/Step08.dat"},
            {"StepMapDataLevel2Stage2Step01.dn", "map/step/level2/stage2/Step01.dat"},
            {"StepMapDataLevel2Stage2Step02.dn", "map/step/level2/stage2/Step02.dat"},
            {"StepMapDataLevel2Stage2Step03.dn", "map/step/level2/stage2/Step03.dat"},
            {"StepMapDataLevel2Stage2Step04.dn", "map/step/level2/stage2/Step04.dat"},
            {"StepMapDataLevel2Stage2Step05.dn", "map/step/level2/stage2/Step05.dat"},
            {"StepMapDataLevel2Stage2Step06.dn", "map/step/level2/stage2/Step06.dat"},
            {"StepMapDataLevel2Stage2Step07.dn", "map/step/level2/stage2/Step07.dat"},
            {"StepMapDataLevel2Stage2Step08.dn", "map/step/level2/stage2/Step08.dat"},
            {"StepMapDataLevel2Stage2Step09.dn", "map/step/level2/stage2/Step09.dat"},
            {"StepMapDataLevel2Stage2Step10.dn", "map/step/level2/stage2/Step10.dat"},
            {"StepMapDataLevel2Stage3Step01.dn", "map/step/level2/stage3/Step01.dat"},
            {"StepMapDataLevel2Stage3Step02.dn", "map/step/level2/stage3/Step02.dat"},
            {"StepMapDataLevel2Stage3Step03.dn", "map/step/level2/stage3/Step03.dat"},
            {"StepMapDataLevel2Stage3Step04.dn", "map/step/level2/stage3/Step04.dat"},
            {"StepMapDataLevel2Stage3Step05.dn", "map/step/level2/stage3/Step05.dat"},
            {"StepMapDataLevel2Stage3Step06.dn", "map/step/level2/stage3/Step06.dat"},
            {"StepMapDataLevel2Stage4Step01.dn", "map/step/level2/stage4/Step01.dat"},
            {"StepMapDataLevel2Stage4Step02.dn", "map/step/level2/stage4/Step02.dat"},
            {"StepMapDataLevel2Stage4Step03.dn", "map/step/level2/stage4/Step03.dat"},
            {"StepMapDataLevel2Stage4Step04.dn", "map/step/level2/stage4/Step04.dat"},
            {"StepMapDataLevel2Stage4Step05.dn", "map/step/level2/stage4/Step05.dat"},
            {"StepMapDataLevel2Stage4Step06.dn", "map/step/level2/stage4/Step06.dat"},
            {"StepMapDataLevel2Stage4Step07.dn", "map/step/level2/stage4/Step07.dat"},
            {"StepMapDataLevel2Stage4Step08.dn", "map/step/level2/stage4/Step08.dat"},
            {"StepMapDataLevel2Stage4Step09.dn", "map/step/level2/stage4/Step09.dat"},
            {"StepMapDataLevel2Stage4Step10.dn", "map/step/level2/stage4/Step10.dat"},
            {"StepMapDataLevel2Stage5Step01.dn", "map/step/level2/stage5/Step01.dat"},
            {"StepMapDataLevel2Stage5Step02.dn", "map/step/level2/stage5/Step02.dat"},
            {"StepMapDataLevel3Stage1Step01.dn", "map/step/level3/stage1/Step01.dat"},
            {"StepMapDataLevel3Stage1Step02.dn", "map/step/level3/stage1/Step02.dat"},
            {"StepMapDataLevel3Stage1Step03.dn", "map/step/level3/stage1/Step03.dat"},
            {"StepMapDataLevel3Stage1Step04.dn", "map/step/level3/stage1/Step04.dat"},
            {"StepMapDataLevel3Stage1Step05.dn", "map/step/level3/stage1/Step05.dat"},
            {"StepMapDataLevel3Stage1Step06.dn", "map/step/level3/stage1/Step06.dat"},
            {"StepMapDataLevel3Stage1Step07.dn", "map/step/level3/stage1/Step07.dat"},
            {"StepMapDataLevel3Stage1Step08.dn", "map/step/level3/stage1/Step08.dat"},
            {"StepMapDataLevel3Stage1Step09.dn", "map/step/level3/stage1/Step09.dat"},
            {"StepMapDataLevel3Stage1Step10.dn", "map/step/level3/stage1/Step10.dat"},
            {"StepMapDataLevel3Stage2Step01.dn", "map/step/level3/stage2/Step01.dat"},
            {"StepMapDataLevel3Stage2Step02.dn", "map/step/level3/stage2/Step02.dat"},
            {"StepMapDataLevel3Stage2Step03.dn", "map/step/level3/stage2/Step03.dat"},
            {"StepMapDataLevel3Stage2Step04.dn", "map/step/level3/stage2/Step04.dat"},
            {"StepMapDataLevel3Stage2Step05.dn", "map/step/level3/stage2/Step05.dat"},
            {"StepMapDataLevel3Stage2Step06.dn", "map/step/level3/stage2/Step06.dat"},
            {"StepMapDataLevel3Stage3Step01.dn", "map/step/level3/stage3/Step01.dat"},
            {"StepMapDataLevel3Stage3Step02.dn", "map/step/level3/stage3/Step02.dat"},
            {"StepMapDataLevel3Stage3Step03.dn", "map/step/level3/stage3/Step03.dat"},
            {"StepMapDataLevel3Stage3Step04.dn", "map/step/level3/stage3/Step04.dat"},
            {"StepMapDataLevel3Stage3Step05.dn", "map/step/level3/stage3/Step05.dat"},
            {"StepMapDataLevel3Stage3Step06.dn", "map/step/level3/stage3/Step06.dat"},
            {"StepMapDataLevel3Stage3Step07.dn", "map/step/level3/stage3/Step07.dat"},
            {"StepMapDataLevel3Stage3Step08.dn", "map/step/level3/stage3/Step08.dat"},
            {"StepMapDataLevel3Stage3Step09.dn", "map/step/level3/stage3/Step09.dat"},
            {"StepMapDataLevel3Stage3Step10.dn", "map/step/level3/stage3/Step10.dat"},
            {"StepMapDataLevel3Stage4Step01.dn", "map/step/level3/stage4/Step01.dat"},
            {"StepMapDataLevel3Stage4Step02.dn", "map/step/level3/stage4/Step02.dat"},
            {"StepMapDataLevel3Stage4Step03.dn", "map/step/level3/stage4/Step03.dat"},
            {"StepMapDataLevel3Stage4Step04.dn", "map/step/level3/stage4/Step04.dat"},
            {"StepMapDataLevel3Stage4Step05.dn", "map/step/level3/stage4/Step05.dat"},
            {"StepMapDataLevel3Stage4Step06.dn", "map/step/level3/stage4/Step06.dat"},
            {"StepMapDataLevel3Stage4Step07.dn", "map/step/level3/stage4/Step07.dat"},
            {"StepMapDataLevel3Stage4Step08.dn", "map/step/level3/stage4/Step08.dat"},
            {"StepMapDataLevel3Stage5Step01.dn", "map/step/level3/stage5/Step01.dat"},
            {"StepMapDataLevel3Stage5Step02.dn", "map/step/level3/stage5/Step02.dat"},
            {"StepMapDataLevel4Stage1Step01.dn", "map/step/level4/stage1/Step01.dat"},
            {"StepMapDataLevel4Stage1Step02.dn", "map/step/level4/stage1/Step02.dat"},
            {"StepMapDataLevel4Stage1Step03.dn", "map/step/level4/stage1/Step03.dat"},
            {"StepMapDataLevel4Stage1Step04.dn", "map/step/level4/stage1/Step04.dat"},
            {"StepMapDataLevel4Stage1Step05.dn", "map/step/level4/stage1/Step05.dat"},
            {"StepMapDataLevel4Stage2Step01.dn", "map/step/level4/stage2/Step01.dat"},
            {"StepMapDataLevel4Stage2Step02.dn", "map/step/level4/stage2/Step02.dat"},
            {"StepMapDataLevel4Stage2Step03.dn", "map/step/level4/stage2/Step03.dat"},
            {"StepMapDataLevel4Stage2Step04.dn", "map/step/level4/stage2/Step04.dat"},
            {"StepMapDataLevel4Stage2Step05.dn", "map/step/level4/stage2/Step05.dat"},
            {"StepMapDataLevel4Stage2Step06.dn", "map/step/level4/stage2/Step06.dat"},
            {"StepMapDataLevel4Stage2Step07.dn", "map/step/level4/stage2/Step07.dat"},
            {"StepMapDataLevel4Stage2Step08.dn", "map/step/level4/stage2/Step08.dat"},
            {"StepMapDataLevel4Stage2Step09.dn", "map/step/level4/stage2/Step09.dat"},
            {"StepMapDataLevel4Stage3Step01.dn", "map/step/level4/stage3/Step01.dat"},
            {"StepMapDataLevel4Stage3Step02.dn", "map/step/level4/stage3/Step02.dat"},
            {"StepMapDataLevel4Stage3Step03.dn", "map/step/level4/stage3/Step03.dat"},
            {"StepMapDataLevel4Stage3Step04.dn", "map/step/level4/stage3/Step04.dat"},
            {"StepMapDataLevel4Stage3Step05.dn", "map/step/level4/stage3/Step05.dat"},
            {"StepMapDataLevel4Stage3Step06.dn", "map/step/level4/stage3/Step06.dat"},
            {"StepMapDataLevel4Stage4Step01.dn", "map/step/level4/stage4/Step01.dat"},
            {"StepMapDataLevel4Stage4Step02.dn", "map/step/level4/stage4/Step02.dat"},
            {"StepMapDataLevel4Stage4Step03.dn", "map/step/level4/stage4/Step03.dat"},
            {"StepMapDataLevel4Stage4Step04.dn", "map/step/level4/stage4/Step04.dat"},
            {"StepMapDataLevel4Stage4Step05.dn", "map/step/level4/stage4/Step05.dat"},
            {"StepMapDataLevel4Stage4Step06.dn", "map/step/level4/stage4/Step06.dat"},
            {"StepMapDataLevel4Stage4Step07.dn", "map/step/level4/stage4/Step07.dat"},
            {"StepMapDataLevel4Stage5Step01.dn", "map/step/level4/stage5/Step01.dat"},
            {"StepMapDataLevel4Stage5Step02.dn", "map/step/level4/stage5/Step02.dat"},
            {"StepMapDataLevel4Stage5Step03.dn", "map/step/level4/stage5/Step03.dat"},
            {"StepMapDataLevel4Stage5Step04.dn", "map/step/level4/stage5/Step04.dat"},
            {"StepMapDataLevel4Stage5Step05.dn", "map/step/level4/stage5/Step05.dat"},
            {"StepMapDataLevel4Stage5Step06.dn", "map/step/level4/stage5/Step06.dat"},
            {"StepMapDataLevel4Stage6Step01.dn", "map/step/level4/stage6/Step01.dat"},
            {"StepMapDataLevel4Stage6Step02.dn", "map/step/level4/stage6/Step02.dat"},
            {"StepMapDataLevel5Stage1Step01.dn", "map/step/level5/stage1/Step01.dat"},
            {"StepMapDataLevel5Stage1Step02.dn", "map/step/level5/stage1/Step02.dat"},
            {"StepMapDataLevel5Stage1Step03.dn", "map/step/level5/stage1/Step03.dat"},
            {"StepMapDataLevel5Stage1Step04.dn", "map/step/level5/stage1/Step04.dat"},
            {"StepMapDataLevel5Stage1Step05.dn", "map/step/level5/stage1/Step05.dat"},
            {"StepMapDataLevel5Stage1Step06.dn", "map/step/level5/stage1/Step06.dat"},
            {"StepMapDataLevel5Stage1Step07.dn", "map/step/level5/stage1/Step07.dat"},
            {"StepMapDataLevel5Stage1Step08.dn", "map/step/level5/stage1/Step08.dat"},
            {"StepMapDataLevel5Stage1Step09.dn", "map/step/level5/stage1/Step09.dat"},
            {"StepMapDataLevel5Stage2Step01.dn", "map/step/level5/stage2/Step01.dat"},
            {"StepMapDataLevel5Stage2Step02.dn", "map/step/level5/stage2/Step02.dat"},
            {"StepMapDataLevel5Stage2Step03.dn", "map/step/level5/stage2/Step03.dat"},
            {"StepMapDataLevel5Stage2Step04.dn", "map/step/level5/stage2/Step04.dat"},
            {"StepMapDataLevel5Stage2Step05.dn", "map/step/level5/stage2/Step05.dat"},
            {"StepMapDataLevel5Stage2Step06.dn", "map/step/level5/stage2/Step06.dat"},
            {"StepMapDataLevel5Stage2Step07.dn", "map/step/level5/stage2/Step07.dat"},
            {"StepMapDataLevel5Stage2Step08.dn", "map/step/level5/stage2/Step08.dat"},
            {"StepMapDataLevel5Stage3Step01.dn", "map/step/level5/stage3/Step01.dat"},
            {"StepMapDataLevel5Stage3Step02.dn", "map/step/level5/stage3/Step02.dat"},
            {"StepMapDataLevel5Stage3Step03.dn", "map/step/level5/stage3/Step03.dat"},
            {"StepMapDataLevel5Stage3Step04.dn", "map/step/level5/stage3/Step04.dat"},
            {"StepMapDataLevel5Stage3Step05.dn", "map/step/level5/stage3/Step05.dat"},
            {"StepMapDataLevel5Stage3Step06.dn", "map/step/level5/stage3/Step06.dat"},
            {"StepMapDataLevel5Stage3Step07.dn", "map/step/level5/stage3/Step07.dat"},
            {"StepMapDataLevel5Stage3Step08.dn", "map/step/level5/stage3/Step08.dat"},
            {"StepMapDataLevel5Stage4Step01.dn", "map/step/level5/stage4/Step01.dat"},
            {"StepMapDataLevel5Stage4Step02.dn", "map/step/level5/stage4/Step02.dat"},
            {"StepMapDataLevel5Stage4Step03.dn", "map/step/level5/stage4/Step03.dat"},
            {"StepMapDataLevel5Stage4Step04.dn", "map/step/level5/stage4/Step04.dat"},
            {"StepMapDataLevel5Stage4Step05.dn", "map/step/level5/stage4/Step05.dat"},
            {"StepMapDataLevel5Stage4Step06.dn", "map/step/level5/stage4/Step06.dat"},
            {"StepMapDataLevel5Stage4Step07.dn", "map/step/level5/stage4/Step07.dat"},
            {"StepMapDataLevel5Stage4Step08.dn", "map/step/level5/stage4/Step08.dat"},
            {"StepMapDataLevel5Stage5Step01.dn", "map/step/level5/stage5/Step01.dat"},
            {"StepMapDataLevel5Stage5Step02.dn", "map/step/level5/stage5/Step02.dat"},
            {"StepMapDataLevel5Stage5Step03.dn", "map/step/level5/stage5/Step03.dat"},
            {"StepMapDataLevel5Stage5Step04.dn", "map/step/level5/stage5/Step04.dat"},
            {"StepMapDataLevel5Stage5Step05.dn", "map/step/level5/stage5/Step05.dat"},
            {"StepMapDataLevel5Stage5Step06.dn", "map/step/level5/stage5/Step06.dat"},
            {"StepMapDataLevel5Stage5Step07.dn", "map/step/level5/stage5/Step07.dat"},
            {"StepMapDataLevel5Stage5Step08.dn", "map/step/level5/stage5/Step08.dat"},
            {"StepMapDataLevel5Stage5Step09.dn", "map/step/level5/stage5/Step09.dat"},
            {"StepMapDataLevel5Stage5Step10.dn", "map/step/level5/stage5/Step10.dat"},
            {"StepMapDataLevel5Stage5Step11.dn", "map/step/level5/stage5/Step11.dat"},
            {"StepMapDataLevel5Stage5Step12.dn", "map/step/level5/stage5/Step12.dat"},
            {"StepMapDataLevel5Stage5Step13.dn", "map/step/level5/stage5/Step13.dat"},
            {"StepMapDataLevel5Stage5Step14.dn", "map/step/level5/stage5/Step14.dat"},
            {"StepMapDataLevel5Stage5Step15.dn", "map/step/level5/stage5/Step15.dat"},
            {"StepMapDataLevel5Stage5Step16.dn", "map/step/level5/stage5/Step16.dat"},
            {"StepMapDataLevel5Stage5Step17.dn", "map/step/level5/stage5/Step17.dat"},
            {"StepMapDataLevel5Stage5Step18.dn", "map/step/level5/stage5/Step18.dat"},
            {"StepMapDataLevel5Stage5Step19.dn", "map/step/level5/stage5/Step19.dat"},
            {"StepMapDataLevel5Stage5Step20.dn", "map/step/level5/stage5/Step20.dat"},
            {"StepMapDataLevel5Stage5Step21.dn", "map/step/level5/stage5/Step21.dat"},
            {"StepMapDataLevel5Stage5Step22.dn", "map/step/level5/stage5/Step22.dat"},
            {"StepMapDataLevel5Stage5Step23.dn", "map/step/level5/stage5/Step23.dat"},
            {"StepMapDataLevel5Stage6Step01.dn", "map/step/level5/stage6/Step01.dat"},
            {"StepMapDataLevel5Stage6Step02.dn", "map/step/level5/stage6/Step02.dat"},
            {"StepMapDataLevel6Stage1Step01.dn", "map/step/level6/stage1/Step01.dat"},
            {"StepMapDataLevel6Stage1Step02.dn", "map/step/level6/stage1/Step02.dat"},
            {"StepMapDataLevel6Stage1Step03.dn", "map/step/level6/stage1/Step03.dat"},
            {"StepMapDataLevel6Stage1Step04.dn", "map/step/level6/stage1/Step04.dat"},
            {"StepMapDataLevel6Stage1Step05.dn", "map/step/level6/stage1/Step05.dat"},
            {"StepMapDataLevel6Stage1Step06.dn", "map/step/level6/stage1/Step06.dat"},
            {"StepMapDataLevel6Stage1Step07.dn", "map/step/level6/stage1/Step07.dat"},
            {"StepMapDataLevel6Stage1Step08.dn", "map/step/level6/stage1/Step08.dat"},
            {"StepMapDataLevel6Stage1Step09.dn", "map/step/level6/stage1/Step09.dat"},
            {"StepMapDataLevel6Stage1Step10.dn", "map/step/level6/stage1/Step10.dat"},
            {"StepMapDataLevel6Stage1Step11.dn", "map/step/level6/stage1/Step11.dat"},
            {"StepMapDataLevel6Stage2Step01.dn", "map/step/level6/stage2/Step01.dat"},
            {"StepMapDataLevel6Stage2Step02.dn", "map/step/level6/stage2/Step02.dat"},
            {"StepMapDataLevel6Stage2Step03.dn", "map/step/level6/stage2/Step03.dat"},
            {"StepMapDataLevel6Stage2Step04.dn", "map/step/level6/stage2/Step04.dat"},
            {"StepMapDataLevel6Stage2Step05.dn", "map/step/level6/stage2/Step05.dat"},
            {"StepMapDataLevel6Stage2Step06.dn", "map/step/level6/stage2/Step06.dat"},
            {"StepMapDataLevel6Stage2Step07.dn", "map/step/level6/stage2/Step07.dat"},
            {"StepMapDataLevel6Stage2Step08.dn", "map/step/level6/stage2/Step08.dat"},
            {"StepMapDataLevel6Stage2Step09.dn", "map/step/level6/stage2/Step09.dat"},
            {"StepMapDataLevel6Stage2Step10.dn", "map/step/level6/stage2/Step10.dat"},
            {"StepMapDataLevel6Stage2Step11.dn", "map/step/level6/stage2/Step11.dat"},
            {"StepMapDataLevel6Stage2Step12.dn", "map/step/level6/stage2/Step12.dat"},
            {"StepMapDataLevel6Stage2Step13.dn", "map/step/level6/stage2/Step12.dat"},
            {"StepMapDataLevel6Stage2Step14.dn", "map/step/level6/stage2/Step14.dat"},
            {"StepMapDataLevel6Stage2Step15.dn", "map/step/level6/stage2/Step15.dat"},
            {"StepMapDataLevel6Stage2Step16.dn", "map/step/level6/stage2/Step16.dat"},
            {"StepMapDataLevel6Stage2Step17.dn", "map/step/level6/stage2/Step17.dat"},
            {"StepMapDataLevel6Stage2Step18.dn", "map/step/level6/stage2/Step18.dat"},
            {"StepMapDataLevel6Stage2Step19.dn", "map/step/level6/stage2/Step19.dat"},
            {"StepMapDataLevel6Stage2Step20.dn", "map/step/level6/stage2/Step20.dat"},
            {"StepMapDataLevel6Stage3Step01.dn", "map/step/level6/stage3/Step01.dat"},
            {"StepMapDataLevel6Stage3Step02.dn", "map/step/level6/stage3/Step02.dat"},
            {"StepMapDataLevel6Stage3Step03.dn", "map/step/level6/stage3/Step03.dat"},
            {"StepMapDataLevel6Stage3Step04.dn", "map/step/level6/stage3/Step04.dat"},
            {"StepMapDataLevel6Stage3Step05.dn", "map/step/level6/stage3/Step05.dat"},
            {"StepMapDataLevel6Stage3Step06.dn", "map/step/level6/stage3/Step06.dat"},
            {"StepMapDataLevel6Stage3Step07.dn", "map/step/level6/stage3/Step07.dat"},
            {"StepMapDataLevel6Stage3Step08.dn", "map/step/level6/stage3/Step08.dat"},
            {"StepMapDataLevel6Stage4Step01.dn", "map/step/level6/stage4/Step01.dat"},
            {"StepMapDataLevel6Stage4Step02.dn", "map/step/level6/stage4/Step02.dat"},
            {"StepMapDataLevel6Stage4Step03.dn", "map/step/level6/stage4/Step03.dat"},
            {"StepMapDataLevel6Stage4Step04.dn", "map/step/level6/stage4/Step04.dat"},
            {"StepMapDataLevel6Stage4Step05.dn", "map/step/level6/stage4/Step05.dat"},
            {"StepMapDataLevel6Stage4Step06.dn", "map/step/level6/stage4/Step06.dat"},
            {"StepMapDataLevel6Stage4Step07.dn", "map/step/level6/stage4/Step07.dat"},
            {"StepMapDataLevel6Stage5Step01.dn", "map/step/level6/stage5/Step01.dat"},
            {"StepMapDataLevel6Stage5Step02.dn", "map/step/level6/stage5/Step02.dat"},
            {"StepMapDataLevel6Stage5Step03.dn", "map/step/level6/stage5/Step03.dat"},
            {"StepMapDataLevel6Stage5Step04.dn", "map/step/level6/stage5/Step04.dat"},
            {"StepMapDataLevel6Stage5Step05.dn", "map/step/level6/stage5/Step05.dat"},
            {"StepMapDataLevel6Stage5Step06.dn", "map/step/level6/stage5/Step06.dat"},
            {"StepMapDataLevel6Stage5Step07.dn", "map/step/level6/stage5/Step07.dat"},
            {"StepMapDataLevel6Stage5Step08.dn", "map/step/level6/stage5/Step08.dat"},
            {"StepMapDataLevel6Stage6Step01.dn", "map/step/level6/stage6/Step01.dat"},
            {"StepMapDataLevel6Stage6Step02.dn", "map/step/level6/stage6/Step02.dat"},
            {"StepMapDataLevel7Stage1Step01.dn", "map/step/level7/stage1/Step01.dat"},
            {"StepMapDataLevel7Stage1Step02.dn", "map/step/level7/stage1/Step02.dat"},
            {"StepMapDataLevel7Stage1Step03.dn", "map/step/level7/stage1/Step03.dat"},
            {"StepMapDataLevel7Stage1Step04.dn", "map/step/level7/stage1/Step04.dat"},
            {"StepMapDataLevel7Stage1Step05.dn", "map/step/level7/stage1/Step05.dat"},
            {"StepMapDataLevel7Stage1Step06.dn", "map/step/level7/stage1/Step06.dat"},
            {"StepMapDataLevel7Stage1Step07.dn", "map/step/level7/stage1/Step07.dat"},
            {"StepMapDataLevel7Stage1Step08.dn", "map/step/level7/stage1/Step08.dat"},
            {"StepMapDataLevel7Stage1Step09.dn", "map/step/level7/stage1/Step09.dat"},
            {"StepMapDataLevel7Stage2Step01.dn", "map/step/level7/stage2/Step01.dat"},
            {"StepMapDataLevel7Stage2Step02.dn", "map/step/level7/stage2/Step02.dat"},
            {"StepMapDataLevel7Stage2Step03.dn", "map/step/level7/stage2/Step03.dat"},
            {"StepMapDataLevel7Stage2Step04.dn", "map/step/level7/stage2/Step04.dat"},
            {"StepMapDataLevel7Stage2Step05.dn", "map/step/level7/stage2/Step05.dat"},
            {"StepMapDataLevel7Stage2Step06.dn", "map/step/level7/stage2/Step06.dat"},
            {"StepMapDataLevel7Stage2Step07.dn", "map/step/level7/stage2/Step07.dat"},
            {"StepMapDataLevel7Stage2Step08.dn", "map/step/level7/stage2/Step08.dat"},
            {"StepMapDataLevel7Stage2Step09.dn", "map/step/level7/stage2/Step09.dat"},
            {"StepMapDataLevel7Stage2Step10.dn", "map/step/level7/stage2/Step10.dat"},
            {"StepMapDataLevel7Stage3Step01.dn", "map/step/level7/stage3/Step01.dat"},
            {"StepMapDataLevel7Stage3Step02.dn", "map/step/level7/stage3/Step02.dat"},
            {"StepMapDataLevel7Stage3Step03.dn", "map/step/level7/stage3/Step03.dat"},
            {"StepMapDataLevel7Stage3Step04.dn", "map/step/level7/stage3/Step04.dat"},
            {"StepMapDataLevel7Stage3Step05.dn", "map/step/level7/stage3/Step05.dat"},
            {"StepMapDataLevel7Stage3Step06.dn", "map/step/level7/stage3/Step06.dat"},
            {"StepMapDataLevel7Stage3Step07.dn", "map/step/level7/stage3/Step07.dat"},
            {"StepMapDataLevel7Stage3Step08.dn", "map/step/level7/stage3/Step08.dat"},
            {"StepMapDataLevel7Stage3Step09.dn", "map/step/level7/stage3/Step09.dat"},
            {"StepMapDataLevel7Stage3Step10.dn", "map/step/level7/stage3/Step10.dat"},
            {"StepMapDataLevel7Stage3Step11.dn", "map/step/level7/stage3/Step11.dat"},
            {"StepMapDataLevel7Stage3Step12.dn", "map/step/level7/stage3/Step12.dat"},
            {"StepMapDataLevel7Stage3Step13.dn", "map/step/level7/stage3/Step13.dat"},
            {"StepMapDataLevel7Stage3Step14.dn", "map/step/level7/stage3/Step14.dat"},
            {"StepMapDataLevel7Stage4Step01.dn", "map/step/level7/stage4/Step01.dat"},
            {"StepMapDataLevel7Stage4Step02.dn", "map/step/level7/stage4/Step02.dat"},
            {"StepMapDataLevel7Stage5Step01.dn", "map/step/level7/stage5/Step01.dat"},
            {"StepMapDataLevel7Stage5Step02.dn", "map/step/level7/stage5/Step02.dat"},
            {"StepMapDataLevel7Stage5Step03.dn", "map/step/level7/stage5/Step03.dat"},
            {"StepMapDataLevel7Stage5Step04.dn", "map/step/level7/stage5/Step04.dat"},
            {"StepMapDataLevel7Stage6Step01.dn", "map/step/level7/stage6/Step01.dat"},
            {"StepMapDataLevel7Stage6Step02.dn", "map/step/level7/stage6/Step02.dat"},
            {"StepMapDataLevel7Stage6Step03.dn", "map/step/level7/stage6/Step03.dat"},
            {"StepMapDataLevel7Stage6Step04.dn", "map/step/level7/stage6/Step04.dat"},
            {"StepMapDataOtherArenaBoss01.dn", "map/step/other/arena/Boss01.dat"},
            {"StepMapDataOtherArenaBoss02.dn", "map/step/other/arena/Boss02.dat"},
            {"StepMapDataOtherArenaBoss03.dn", "map/step/other/arena/Boss03.dat"},
            {"StepMapDataOtherArenaBoss04.dn", "map/step/other/arena/Boss04.dat"},
            {"StepMapDataOtherArenaBoss05.dn", "map/step/other/arena/Boss05.dat"},
            {"StepMapDataOtherArenaBoss06.dn", "map/step/other/arena/Boss06.dat"},
            {"StepMapDataOtherArenaBoss07.dn", "map/step/other/arena/Boss07.dat"},
            {"StepMapDataOtherArenaBoss08.dn", "map/step/other/arena/Boss08.dat"},
            {"StepMapDataOtherArenaBoss09.dn", "map/step/other/arena/Boss09.dat"},
            {"StepMapDataOtherArenaBoss10.dn", "map/step/other/arena/Boss10.dat"},
            {"StepMapDataOtherArenaBoss11.dn", "map/step/other/arena/Boss11.dat"},
            {"StepMapDataOtherArenaBoss12.dn", "map/step/other/arena/Boss12.dat"},
            {"StepMapDataOtherArenaRoom01.dn", "map/step/other/arena/Room01.dat"},
            {"StepMapDataOtherArenaBoss12s.dn", "map/step/other/arena/Boss12s.dat"},
            {"StepMapDataOtherArenaEntrance01.dn", "map/step/other/arena/Entrance01.dat"},
            {"StepMapDataOtherArenaexBoss01.dn", "map/step/other/arenaex/Boss01.dat"},
            {"StepMapDataOtherArenaexBoss02.dn", "map/step/other/arenaex/Boss02.dat"},
            {"StepMapDataOtherArenaexBoss03.dn", "map/step/other/arenaex/Boss03.dat"},
            {"StepMapDataOtherArenaexBoss04.dn", "map/step/other/arenaex/Boss04.dat"},
            {"StepMapDataOtherArenaexBoss05.dn", "map/step/other/arenaex/Boss05.dat"},
            {"StepMapDataOtherArenaexBoss06.dn", "map/step/other/arenaex/Boss06.dat"},
            {"StepMapDataOtherArenaexBoss07.dn", "map/step/other/arenaex/Boss07.dat"},
            {"StepMapDataOtherArenaexBoss08.dn", "map/step/other/arenaex/Boss08.dat"},
            {"StepMapDataOtherArenaexBoss09.dn", "map/step/other/arenaex/Boss09.dat"},
            {"StepMapDataOtherArenaexBoss10.dn", "map/step/other/arenaex/Boss10.dat"},
            {"StepMapDataOtherArenaexBoss11.dn", "map/step/other/arenaex/Boss11.dat"},
            {"StepMapDataOtherArenaexBoss12.dn", "map/step/other/arenaex/Boss12.dat"},
            {"StepMapDataOtherArenaexBoss12s.dn", "map/step/other/arenaex/Boss12s.dat"},
            {"StepMapDataOtherArenaexBoss13.dn", "map/step/other/arenaex/Boss13.dat"},
            {"StepMapDataOtherArenaexBoss14.dn", "map/step/other/arenaex/Boss14.dat"},
            {"StepMapDataOtherArenaexRoom01.dn", "map/step/other/arenaex/Room01.dat"},
            {"StepMapDataOtherArenaexRoom02.dn", "map/step/other/arenaex/Room01.dat"},
            {"StepMapDataOtherArenaexEntrance01.dn", "map/step/other/challenge/stage01/Entrance01.dat"},
            {"StepMapDataOtherLvmapLevel01.dn", "map/step/other/lvmap/Level01.dat"},
            {"StepMapDataOtherLvmapLevel02.dn", "map/step/other/lvmap/Level02.dat"},
            {"StepMapDataOtherLvmapLevel03.dn", "map/step/other/lvmap/Level03.dat"},
            {"StepMapDataOtherLvmapLevel04.dn", "map/step/other/lvmap/Level04.dat"},
            {"StepMapDataOtherLvmapLevel05.dn", "map/step/other/lvmap/Level05.dat"},
            {"StepMapDataOtherLvmapLevel06.dn", "map/step/other/lvmap/Level06.dat"},
            {"StepMapDataOtherLvmapLevel07.dn", "map/step/other/lvmap/Level07.dat"},
            {"StepMapDataOtherShipAbility01.dn", "map/step/other/ship/Ability01.dat"},
            {"StepMapDataOtherShipAbility02.dn", "map/step/other/ship/Ability02.dat"},
            {"StepMapDataOtherShipAbility03.dn", "map/step/other/ship/Ability03.dat"},
            {"StepMapDataOtherShipAbility04.dn", "map/step/other/ship/Ability04.dat"},
            {"StepMapDataOtherShipIn01.dn", "map/step/other/ship/In01.dat"},
            {"StepMapDataOtherShipIn02.dn", "map/step/other/ship/In02.dat"},
            {"StepMapDataOtherShipIn03.dn", "map/step/other/ship/In03.dat"},
            {"StepMapDataOtherShipIn04.dn", "map/step/other/ship/In04.dat"},
            {"StepMapDataOtherShipIn05.dn", "map/step/other/ship/In05.dat"},
            {"StepMapDataOtherShipIn06.dn", "map/step/other/ship/In06.dat"},
            {"StepMapDataOtherShipOut01.dn", "map/step/other/ship/Out01.dat"},
            {"StepMapDataOtherShipOut02.dn", "map/step/other/ship/Out02.dat"},
            {"StepMapDataOtherShipOut03.dn", "map/step/other/ship/Out03.dat"},
            {"StepMapDataChallengeStage01Step01.dn", "map/step/other/challenge/stage01/Step01.dat"},
            {"StepMapDataChallengeStage01Step02.dn", "map/step/other/challenge/stage01/Step02.dat"},
            {"StepMapDataChallengeStage01Step03.dn", "map/step/other/challenge/stage01/Step03.dat"},
            {"StepMapDataChallengeStage01Step04.dn", "map/step/other/challenge/stage01/Step04.dat"},
            {"StepMapDataChallengeStage03Step01.dn", "map/step/other/challenge/stage03/Step01.dat"},
            {"StepMapDataChallengeStage03Step02.dn", "map/step/other/challenge/stage03/Step02.dat"},
            {"StepMapDataChallengeStage03Step03.dn", "map/step/other/challenge/stage03/Step03.dat"},
            {"StepMapDataChallengeStage03Step04.dn", "map/step/other/challenge/stage03/Step04.dat"},
            {"StepMapDataChallengeStage04Step01.dn", "map/step/other/challenge/stage04/Step01.dat"},
            {"StepMapDataChallengeStage04Step02.dn", "map/step/other/challenge/stage04/Step02.dat"},
            {"StepMapDataChallengeStage04Step03.dn", "map/step/other/challenge/stage04/Step03.dat"},
            {"StepMapDataChallengeStage04Step04.dn", "map/step/other/challenge/stage04/Step04.dat"},
            {"StepMapDataChallengeStage06Step01.dn", "map/step/other/challenge/stage06/Step01.dat"},
            {"StepMapDataChallengeStage06Step02.dn", "map/step/other/challenge/stage06/Step02.dat"},
            {"StepMapDataChallengeStage06Step03.dn", "map/step/other/challenge/stage06/Step03.dat"},
            {"StepMapDataChallengeStage07Step01.dn", "map/step/other/challenge/stage07/Step01.dat"},
            {"StepMapDataChallengeStage07Step02.dn", "map/step/other/challenge/stage07/Step02.dat"},
            {"StepMapDataChallengeStage07Step03.dn", "map/step/other/challenge/stage07/Step03.dat"},
            {"StepMapDataChallengeStage07Step04.dn", "map/step/other/challenge/stage07/Step04.dat"},
            {"StepMapDataChallengeStage08Step01.dn", "map/step/other/challenge/stage08/Step01.dat"},
            {"StepMapDataChallengeStage08Step02.dn", "map/step/other/challenge/stage08/Step02.dat"},
            {"StepMapDataChallengeStage08Step03.dn", "map/step/other/challenge/stage08/Step03.dat"},
            {"StepMapDataChallengeStage08Step04.dn", "map/step/other/challenge/stage08/Step04.dat"},
            {"StepMapDataChallengeStage08Step05.dn", "map/step/other/challenge/stage08/Step05.dat"},
            {"StepMapDataChallengeStage08Step06.dn", "map/step/other/challenge/stage08/Step06.dat"},
            {"StepMapDataChallengeStage10Step01.dn", "map/step/other/challenge/stage10/Step01.dat"},
            {"StepMapDataChallengeStage10Step02.dn", "map/step/other/challenge/stage10/Step02.dat"},
            {"StepMapDataChallengeStage10Step03.dn", "map/step/other/challenge/stage10/Step03.dat"},
            {"StepMapDataChallengeStage10Step04.dn", "map/step/other/challenge/stage10/Step04.dat"}
        };
    }
}
